### ISSUE TITLE
[SUGGESTION] Exit for maze

### ISSUE THREAD

**Issue by Foufou10** [Gorgious56/MazeGenerator#3]
Being able to tell the maze to create an exit (so your plugin can be used for video games)

**Comment by Gorgious56** [comment]
Thanks for the feedback ! 

It is actually already possible in the code but I didn't expose this feature. I will have some time to work on it this week-end so you can expect an update next week. 

Cheers !

**Comment by Gorgious56** [comment]
Hello, Quick question though.

How would you want to have it ? 
For example now if you want to force an exit, you can go into edit mode and remove one of the walls. 

Would that be sufficient ? What did you have in mind ?

Cheers

**Comment by SirHaxe** [comment]
With all my might i will necro this thread!
perhaps let the script randomly choose a wall to exit?

**Comment by Gorgious56** [comment]
That could do it, yeah !

In the meantime you can go into edit mode while the walls object is selected, and delete edges where you want the start and end to be. Since all cells are connected by at least 1 path, you're sure to have at least a working solution.

![image](https://user-images.githubusercontent.com/25156105/123847140-7e83b200-d916-11eb-8b4e-6483c73323a4.png)
![image](https://user-images.githubusercontent.com/25156105/123847186-94917280-d916-11eb-91b2-f6f47108dc3a.png)
![image](https://user-images.githubusercontent.com/25156105/123847336-c7d40180-d916-11eb-8612-50a2cded1f6a.png)

**Comment by Gorgious56** [comment]
I've released a new version with this feature (roughly) implemented.

If you go down into the Path panel, you will be able to select "Random" path and enable "Force Outside Solution" or "Custom" and choose your own path. If using "Random" tweaking the seed will re-evaluate the random in and out solutions of the maze.

![image](https://user-images.githubusercontent.com/25156105/125907195-b6755042-8e00-4441-8014-fbc17b158697.png)

![BSE_25](https://user-images.githubusercontent.com/25156105/125907425-d118c5f4-a68d-4cef-9d5f-f74c28e20cfe.gif)

I'm closing this issue for now as solved. :) Feel free to raise a new one if you see a possible improvement.
